[workspace]
members = [
    "crates/*",
]

[workspace.scripts]
test = "snforge"

[workspace.tool.snforge]
exit_first = true

[workspace.dependencies]
starknet = "2.3.1"

[workspace.package]
version = "0.1.0"

[package]
name = "workspaces"
version.workspace = true

[scripts]
test.workspace = true

[tool]
snforge.workspace = true

[dependencies]
starknet.workspace = true
fibonacci = { path = "crates/fibonacci" }
addition = { path = "crates/addition" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "27fbf5b" }

[[target.starknet-contract]]
