name: My workflow
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@tomek/9-scarb-lock-cache
        with:
          scarb-version: "2.3.1"
      - name: echo_gh_workspace
        run: echo ${GITHUB_WORKSPACE} && echo $GITHUB_WORKSPACE
      - name: smth
        run: ls
      - name: cwd
        run: scarb fmt --check && ls -la
        working-directory: ./crates/addition
#      - run: scarb fmt --check
#      - name: hmm
#        run: ls -la
