name: My workflow
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@d5662ae550db5c58be118aa1b07462a7fd58abec
        with:
          scarb-version: "2.3.1"
      - run: scarb fmt --check
#      - name: cwd
#        run: scarb fmt --check && ls -la
#        working-directory: ./crates/addition
#      - name: hmm
#        run: ls -la
